# Generated by Django 5.1.2 on 2024-10-08 20:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_remove_question_survey_survey_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondent',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
